config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root "shops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions:      'admins/sessions',
  }
  
  namespace :admins do
    resources :shops
  end

  get 'map/show_shops', to: 'map#show_shops'
  
  resources :shops,          only: [:index, :show] do
    resources :reviews,        only: [:index, :new, :create, :show, :destroy, :edit, :update], shallow: true
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
end

app/models/shop.rb
class Shop < ApplicationRecord
  extend Enumerize
  has_many :reviews, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 60 }
  validates :address, presence: true, length: { maximum: 200 }
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90, allow_blank: true }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180, allow_blank: true }
  #後で変更する
  validates :genre, presence: true
  enumerize :genre, in: [:japanese_food, :western_food, :chinese_food, :italian_food, :pub, :bar]

  scope :sort_by_highest_rate, -> { group(:review_id).count }

  def average_rating
    # Review.where(shop_id: shop.id).group(:shop_id).select(:shop_id, 'avg(*) as avg')
    reviews.average(:rate)
  end

  def self.latest(shops)
    shops.order(created_at: :DESC)
  end

  def self.sort_by_count_of_reviews(shops)
    Review.where(shop_id: shops.ids).group(:shop_id).includes(:shop).select(:shop_id, 'count(*) as c').order(c: :desc).map{|review| review.shop}
  end

  def self.sort_by_average_rating(shops)
    Review.where(shop_id: shops.ids).group(:shop_id).includes(:shop).select(:shop_id, 'avg(rate) as avg').order(avg: :desc).map{|review| review.shop}
  end

  def update_lat_and_long
    if image? && exif_data_exists_in_image?
      lat_deg  = to_deg(Magick::ImageList.new('public'+image.url).get_exif_by_entry('GPSLatitude')[0][1].split(','))
      long_deg = to_deg(Magick::ImageList.new('public'+image.url).get_exif_by_entry('GPSLongitude')[0][1].split(','))
      update_columns(latitude: lat_deg, longitude: long_deg)
    end
  end

  def exif_data_exists_in_image?
    Magick::ImageList.new('public'+image.url).get_exif_by_entry('GPSLatitude')[0][1].present?
  end

  def to_deg(dms)
    (Rational(dms[0]) + Rational(dms[1])/60 + Rational(dms[2])/3600).to_f
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/admins/shops_controller.rb
class Admins::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      @shop.update_lat_and_long
      flash[:notice] = "店舗の登録に成功しました"
      redirect_to @shop
    else
      flash.now[:alert] = "店舗の登録に失敗しました"
      render 'new', status: :unprocessable_entity
    end
  end
  
  def edit
    @shop = Shop.find(params[:id])
  end
  
  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      @shop.update_lat_and_long
      flash[:notice] = "店舗の編集に成功しました。"
      redirect_to root_path
    else
      flash[:alert] = "店舗の編集に失敗しました。"
      render 'edit', status: :unprocessable_entity
    end
  end
  
  def destroy
    @shop = Shop.find(params[:id])
    if @shop.destroy
      flash[:notice] = "店舗の削除に成功しました。"
      redirect_to root_path
    else
      flash[:alert] = "店舗の削除に失敗しました。"
      redirect_to root_path
    end
  end
  
  private
  
  def shop_params
    params.require(:shop).permit(:name, :image, :address, :genre)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_q, only: :index
  def index
    @shops = @q.result
    if params[:sort_order] == 'most_rating'
      @shops = Shop.sort_by_count_of_reviews(@shops)
    elsif params[:sort_order] == 'highest_rating'
      @shops = Shop.sort_by_average_rating(@shops)
    else
      @shops = Shop.latest(@shops)
    end
    # kaminariのページネーション
    # @shops = @shops.page(params[:page]).per(20)
  end

  def show
    @shop = Shop.find(params[:id])
    @reviews = @shop.reviews.page(params[:page]).per(20) 
    @total_reviews_count = @shop.reviews.count
  end

  def set_q
    @q = Shop.ransack(params[:q])
  end
end

app/helpers/admins/shops_helper.rb
module Admins::ShopsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def genre(key)
    case key
    when "japanese_food"
      "和食"
    when "western_food"
      "洋食"
    when "chinese_food"
      "中華"
    when "italian_food"
      "イタリアン"
    when "pub"
      "居酒屋"
    when "bar"
      "バー"
    end
  end
end

app/views/shops/index.html.erb
<h1 class="text-center" style="margin: 40px 0;">飲食店一覧</h1>

  <h2 class="search-shop">検索条件</h2>
  
  <%= form_with model: @q, url: shops_path, method: :get do |f| %>
    <div class="row mb-5">
      <div class="col-4">
        <%= f.search_field :name_cont, placeholder: "店名、キーワドを検索" %>
      </div>
        <div class="col-6">
          <ul class="list-group list-group-horizontal">
            <li class="list-group-item active">
              並び順<i class="fa-solid fa-arrow-down-wide-short"></i>
            </li>
            <li class="list-group-item">
              <%= label_tag "sort_order_none", '指定なし' %>
              <%= radio_button_tag "sort_order", "none", params[:sort_order] == 'none' || params[:sort_order].nil? %>
            </li>
            <li class="list-group-item">
              <%= label_tag "sort_order_most_rating", '評価の多い順' %>
              <%= radio_button_tag "sort_order", "most_rating", params[:sort_order] == 'most_rating' %>
            </li>
            <li class="list-group-item">
              <%= label_tag "sort_order_highest_rating", '評価の高い順' %>
              <%= radio_button_tag "sort_order", "highest_rating", params[:sort_order] == 'highest_rating' %>
            </li>
          </ul>
        </div>
      <div class="col-2">
        <%= f.submit '検索', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
      <% @shops.each_with_index do |shop, index| %>
        <div class="col">
          <%= link_to shop_path(shop) do %>
            <div class="card h-100">
              <%= image_tag shop.image.url, class: "card-img-top", alt: "", size: "" %>
              <div class="card-body">
                <h5 style="margin: 15px 0;" class="card-title">店名：<%= shop.name %></h5>
                <h5 style="margin: 15px 0;" class="card-title show-star"><%= shop.reviews.average(:rate) %></h5>
                <p style="margin: 15px 0;" class="card-text">住所：<%= shop.address %></p>
                <% if admin_signed_in? %>
                  <div class="shop-button">
                    <%= button_to "店舗編集", edit_admins_shop_path(shop), class: "btn btn-primary", method: :get %>
                    <%= button_to "店舗削除", admins_shop_path(shop), class: "btn btn-danger", method: :delete  %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/shops/show.html.erb
<div class="shop-show">
  <div class="col-md-8">
    <h2 style="margin: 15px 0;">店名：<%= @shop.name %></h2>
  </div>

  <div class="col-md-8">
    <p style="margin: 15px 0;">住所：<%= @shop.address %></p>
  </div>

  <div class="col-md-8">
    <p style="margin: 15px 0;">投稿件数： <%= @total_reviews_count %>件</p>
  </div>

  <div class="col-md-8">
    <p style="margin: 15px 0;">ジャンル： <%= genre(@shop.genre) %></p>
  </div>

  <br>
  <%= paginate @reviews %>
  <!--ページ幅に合わせてカードの列数を減少させる-->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
    <div class="col">
      <%= link_to new_shop_review_path(shop_id: @shop.id) do %>
        <div class="card h-100">
          <div class="card-body text-center d-flex flex-column align-items-center justify-content-center">
            <h1 class="card-title">＋</h1>
          </div>
        </div>
      <% end %>
    </div>
    <% @reviews.each do |review| %>
      <div class="col">
        <div class="card h-100">
          <a href="<%= review_path(review) %>">
            <%= image_tag review.image.url, class: "card-img-top", alt: "", size: "" %>
          </a>
          <div class="card-body">
            <h5 class="card-title show-star"><%= review.rate %></h5>
            <p class="card-text">コメント：<%= review.comment %></p>
            <!-- ↓↓↓モーダルのトリガーボタン↓↓↓ -->
            <% if current_user && current_user.id == review.user_id %>
              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="<%= "#review_modal_#{review.id}" %>">
                削除
              </button>
            <% end %>
            <!-- ↓↓↓編集ボタン & editページへの遷移↓↓↓ -->
            <% if current_user && current_user.id == review.user_id %>
              <%= link_to "編集", edit_review_path(review), class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
      <!--モーダルの実装-->
      <div class="modal fade" id="<%= "review_modal_#{review.id}" %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" >削除しますか？</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ＊削除したら元には戻せません
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
              <%= button_to '削除する', review, method: :delete, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br><br>