config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root "shops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions:      'admins/sessions',
  }
  
  namespace :admins do
    resources :shops
  end

  get 'map/show_shops', to: 'map#show_shops'
  
  resources :shops,          only: [:index, :show] do
    resources :reviews,        only: [:index, :new, :create, :show, :destroy, :edit, :update], shallow: true
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :name, presence: true, length: { maximum: 50 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
        if resource.active_for_authentication?
            set_flash_message! :notice, :signed_up
            sign_up(resource_name, resource)
            respond_with resource, location: after_sign_up_path_for(resource)
        else
            set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
            expire_data_after_sign_in!
            respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
    else
        flash.now[:alert] = "新規登録に失敗しました"
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource, status: :see_other # 登録失敗時のrespond_withにerror出したいので、ここで303 statusを追加
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name), status: :see_other }
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.page(params[:page]).per(20) 
    @total_reviews_count = @user.reviews.count
  end
  
  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'following'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<h1>Followers</h1>
<br>
<% @users.each do |user| %>
  <%= link_to user_path(user), style: "text-decoration: none; color: black;", class: "card-anchor" do %>
    <div class="card text-center" style="width: 26rem; height: 6rem;">
      <div class="card-body d-flex align-items-center justify-content-between"> 
        <%= turbo_frame_tag "user_name", class: "user-name-in-review" do %>
          <%= user.name %>
        <% end %>
        <div class="review-count-follow">
          <%= user.reviews.count %> reviews
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<br><br><br>

app/views/users/following.html.erb
<h1>Followiing</h1>
<br>
<% @users.each do |user| %>
  <%= link_to user_path(user), style: "text-decoration: none; color: black;", class: "card-anchor" do %>
    <div class="card text-center" style="width: 26rem; height: 6rem;">
      <div class="card-body d-flex align-items-center justify-content-between"> 
        <%= turbo_frame_tag "user_name", class: "user-name-in-review" do %>
          <%= user.name %>
        <% end %>
        <div class="review-count-follow">
          <%= user.reviews.count %> reviews
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<br><br><br>

app/views/users/show.html.erb
<br>
<div class="card" style="width: 25rem; height: 5rem;"> 
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center">
      <div class="flex-grow-1">
        <%= turbo_frame_tag "user_name", class: "user-name-in-review" do %>
          <%= link_to @user.name, user_path(@user), style: "text-decoration: none; color: black; white-space: nowrap;" %>
        <% end %>
      </div>
      <div>
        <% if user_signed_in? && current_user != @user %>
          <%= turbo_frame_tag "follow_button", class: (current_user.following?(@user) ? "unfollow-btn" : "follow-btn") do %>
            <% if current_user.following?(@user) %>
              <%= render 'relationships/unfollow', locals: { user: @user } %>
            <% else %>
              <%= render 'relationships/follow', locals: { user: @user } %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<div class="stats" style= "margin-left: 10px;">
  <a href="<%= following_user_path(@user) %>" style="text-decoration: none; color: black;">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>" style="text-decoration: none; color: black;">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

<br><br>
<div class="col-md-8">
  <h5>投稿件数： <%= @total_reviews_count %>件</h5>
</div>

<br>
<%= paginate @reviews %>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
  <% @reviews.each do |review| %>
    <div class="col">
      <div class="card h-100">
        <a href="<%= review_path(review) %>">
          <%= image_tag review.image.url, class: "card-img-top", alt: "", size: "" %>
        </a>
        <div class="card-body">
          <h5 class="card-title">評価：<%= review.rate %></h5>
          <p class="card-text">コメント：<%= review.comment %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br><br>