config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root "shops#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
  }
  
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions:      'admins/sessions',
  }
  
  namespace :admins do
    resources :shops
  end

  get 'map/show_shops', to: 'map#show_shops'
  
  resources :shops,          only: [:index, :show] do
    resources :reviews,        only: [:index, :new, :create, :show, :destroy, :edit, :update], shallow: true
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_admin_logout_modal.html.erb
<!-- ログアウトのモーダル -->
<div class="modal fade" id="adminLogoutModal" tabindex="-1" aria-labelledby="adminLogoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>本当に管理者アカウントからログアウトしますか？</p>
      </div>
      <div class="modal-footer">
        <%= button_to 'ログアウト', destroy_admin_session_path, method: :get, class: "btn btn-primary" %>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer bg-warning text-dark">
    <p>&copy;2023 solo-log</p>
  <div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container-lg">
      <%= link_to 'ソロログ', root_path, class: "nav-link, navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup" >
        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%= link_to '飲食店一覧', shops_path, method: :get, class: "nav-link" %>
            <%= link_to '地図からお店を探す', map_show_shops_path, method: :get, class: "nav-link" %>
            <button type="button" class="btn btn-warning nav-link text-start" data-bs-toggle="modal" data-bs-target="#userLogoutModal">
              ログアウト
            </button>
            <%= render 'layouts/user_logout_modal' %>
          <% elsif admin_signed_in? %>
            <%= link_to '飲食店一覧', root_path, method: :get, class: "nav-link" %>
            <%= link_to '地図からお店を探す', map_show_shops_path, method: :get, class: "nav-link" %>
            <%= link_to '店舗作成', new_admins_shop_path, method: :get, class: "nav-link" %>
            <button type="button" class="btn btn-warning nav-link text-start" data-bs-toggle="modal" data-bs-target="#adminLogoutModal">
              管理画面ログアウト
            </button>
            <%= render 'layouts/admin_logout_modal' %>
          <% else %>
            <%= link_to '飲食店一覧', shops_path, method: :get, class: "nav-link" %>
            <%= link_to '地図からお店を探す', map_show_shops_path, method: :get, class: "nav-link" %>
            <%= link_to '新規登録', new_user_registration_path, method: :get, class: "nav-link" %>
            <%= link_to 'ログイン', new_user_session_path, method: :get, class: "nav-link" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_logout_modal.html.erb
<!-- ログアウトのモーダル -->
<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="logoutModalLabel">ログアウト</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>本当にログアウトしますか？</p>
      </div>
      <div class="modal-footer">
        <%= button_to 'ログアウト', destroy_user_session_path, method: :get, class: "btn btn-primary" %>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_user_logout_modal.html.erb
<!-- ログアウトのモーダル -->
<div class="modal fade" id="userLogoutModal" tabindex="-1" aria-labelledby="userLogoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="userLogoutModalLabel">ログアウト</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>本当にログアウトしますか？</p>
      </div>
      <div class="modal-footer">
        <%= button_to 'ログアウト', destroy_user_session_path, method: :get, class: "btn btn-primary" %>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_validation_errors.html.erb
<% if model.errors.full_messages.present? %>
  <ul class="alert alert-danger validation-error-list">
    <% model.errors.full_messages.each do |error| %>
      <strong><li><%= error %></li></strong>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoloLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" %>
    <%= javascript_importmap_tags %>
    <%= include_gon %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flashes' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>

  <script>
    // 五段階評価のラベルの数字を全て削除
    const allStarElements = document.querySelectorAll('.star-rate');
    for (let i=0; i<allStarElements.length; i++) {
      allStarElements[i].lastElementChild.innerHTML = '';
    }


    function starRate(event) {
      const starElement = event.target.parentElement;
      const starElements = starElement.parentElement.getElementsByClassName('star-rate');
      starElement.firstElementChild.checked = true;
      uncheckAllStars(starElements);
      checkOrLessSelected(starElements, starElement);
      starElement.classList.add('checked-star')
    }

    function uncheckAllStars(starElements) {
      for (let i=0; i<starElements.length; i++) {
        starElements[i].classList.remove('checked-star');
      }
    }

    function checkOrLessSelected(starElements, starElement) {
      let indexSelectedStar = 0;
      for (let i=0; i<starElements.length; i++) {
        if (starElements[i] === starElement) {
          indexSelectedStar = i;
          break;
        }
      }
      for (let i=0; i<indexSelectedStar; i++) {
        starElements[i].classList.add('checked-star');
      }
    }

    window.onload = function onLoad() {
      let rates = document.querySelectorAll('.show-star');
      for (let i=0; i<rates.length; i++) {
        let html = ""
        let j=0;
        for (; j<Math.floor(rates[i].innerText); j++) {
          html += "<div class='star d-inline-block'></div>";
        }
        // debugger
        if (rates[i].innerHTML-j > 0) {
          html += "<div class='fa-regular fa-star-half-stroke'></div>"
          j++
        }

        for (;j<5; j++) {
          html += "<div class='fa-regular fa-star'></div>";
        }

        rates[i].innerHTML = html;
      }
    }

  </script>

</html>